# Site settings
title: thomasswilliams Blog
description: > 
  Thomas Williams blog from Melbourne, Australia. Tech and life. Previously at Blogger and TheRuntime.
baseurl: ""
url: "https://thomasswilliams.github.io"
author: "Thomas Williams"
license: "This work licensed under a Creative Commons Attribution 4.0 International License."

# Build settings
markdown: kramdown

sass:
  style: compressed