# Site settings
title: Thomas Williams blog
description: > 
  Thomas Williams blog from Hobart, Tasmania.
baseurl: ""
url: "https://thomasswilliams.github.io"
author: "Thomas Williams"
license: "This work licensed under a Creative Commons Attribution 4.0 International License."

# Build settings
markdown: kramdown

sass:
  style: compressed